//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionProyecto_Personal
    {
        public int IdAsignacion { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public Nullable<int> Cod_cargo { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<int> EstadoAsignacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
