//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion_Gasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autorizacion_Gasto()
        {
            this.AUTORIZACION_GASTO_DETALLE = new HashSet<AUTORIZACION_GASTO_DETALLE>();
        }
    
        public int IdAutorizacion { get; set; }
        public string Nro_autorizacion { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<System.DateTime> Fecha_autorizacion { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> Monto_acumulado_autorizaciones_anteriores { get; set; }
        public Nullable<decimal> Saldo_disponible_proyecto { get; set; }
        public Nullable<decimal> Monto_autorizacion { get; set; }
        public Nullable<decimal> Saldo_despues_autorizacion { get; set; }
        public Nullable<decimal> Distribucion_transferencia { get; set; }
        public Nullable<decimal> Distribucion_efectivo { get; set; }
        public Nullable<decimal> Distribucion_otros { get; set; }
        public string Ht { get; set; }
        public Nullable<int> Anio_ht { get; set; }
        public Nullable<int> Estado_documento { get; set; }
        public Nullable<int> Estado { get; set; }
        public int IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
        public Nullable<int> Tipo_autorizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTORIZACION_GASTO_DETALLE> AUTORIZACION_GASTO_DETALLE { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
