//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoAdenda = new HashSet<ContratoAdenda>();
        }
    
        public int IdContrato { get; set; }
        public int IdPersona { get; set; }
        public string DireccionContrato { get; set; }
        public Nullable<int> AnioContrato { get; set; }
        public string NroContrato { get; set; }
        public Nullable<int> IdTipoContrato { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public Nullable<int> IdOficinaDependencia { get; set; }
        public string EjecucionTrabajoSupervision { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> IdLugarPrestacionServicios { get; set; }
        public Nullable<decimal> MontoContrato { get; set; }
        public Nullable<decimal> MontoMensual { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> IdRepresentanteLegal { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual LugarPrestacionServicios LugarPrestacionServicios { get; set; }
        public virtual OficinaDependencia OficinaDependencia { get; set; }
        public virtual RepresentanteLegal RepresentanteLegal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAdenda> ContratoAdenda { get; set; }
    }
}
