//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desembolso
    {
        public int IdDesembolso { get; set; }
        public int IdProyecto { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> NroDesembolso { get; set; }
        public Nullable<System.DateTime> FechaDesembolso { get; set; }
        public string HT { get; set; }
        public string DocumentoDesembolso { get; set; }
        public string NroExpedienteSIAF { get; set; }
        public string Nombre_documento { get; set; }
        public string Nombre_real_documento { get; set; }
        public string Ruta_documento { get; set; }
        public Nullable<decimal> MontoDesembolsado { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
