//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesembolsoVSJustificado
    {
        public Nullable<long> Nro { get; set; }
        public int IdProyecto { get; set; }
        public string Programa { get; set; }
        public string Ubigeo { get; set; }
        public string cod_dep { get; set; }
        public string cod_prov { get; set; }
        public string cod_dist { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Localidad { get; set; }
        public string Snip { get; set; }
        public string CUI { get; set; }
        public string Nom_proyecto { get; set; }
        public Nullable<decimal> Mto_proyecto { get; set; }
        public decimal Desembolso { get; set; }
        public decimal Autorizacion { get; set; }
        public decimal AutorizacionGestionada { get; set; }
        public decimal Manifiesto { get; set; }
        public decimal ManifiestoGestionado { get; set; }
        public decimal Porcentaje { get; set; }
        public string Liquidador { get; set; }
        public Nullable<int> AnioEjecucion { get; set; }
        public string Grupo { get; set; }
    }
}
