//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesembolsoProgramadoMensual
    {
        public int IdDesembolsoProgramadoMensual { get; set; }
        public Nullable<int> IdProgramadoAnual { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<decimal> ROProgramado { get; set; }
        public Nullable<decimal> ROOCProgramado { get; set; }
        public Nullable<decimal> RO { get; set; }
        public Nullable<decimal> ROOC { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual DesembolsoProgramadoAnual DesembolsoProgramadoAnual { get; set; }
    }
}
