//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesembolsoProgramadoAnual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesembolsoProgramadoAnual()
        {
            this.DesembolsoProgramadoMensual = new HashSet<DesembolsoProgramadoMensual>();
        }
    
        public int IdProgramadoAnual { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<decimal> RO { get; set; }
        public Nullable<decimal> ROOC { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesembolsoProgramadoMensual> DesembolsoProgramadoMensual { get; set; }
    }
}
