//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSeguimientoJASS
    {
        public int IdDetalleSeguimientoJASS { get; set; }
        public int IdSeguimientoJASS { get; set; }
        public int IdTipoSeguimiento { get; set; }
        public int IdTipoBienArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string InformeConformidadAC_HT { get; set; }
        public string InformeConformidadAC_Nro { get; set; }
        public Nullable<System.DateTime> InformeConformidadAC_Fecha { get; set; }
        public Nullable<System.DateTime> InformeConformidadAC_FechaGDrive { get; set; }
        public string ActaEntrega_Nro { get; set; }
        public Nullable<System.DateTime> ActaEntrega_Fecha { get; set; }
        public Nullable<System.DateTime> ActaEntrega_FechaGDrive { get; set; }
        public string AcuerdoConsejo_Nro { get; set; }
        public Nullable<System.DateTime> AcuerdoConsejo_Fecha { get; set; }
        public Nullable<System.DateTime> AcuerdoConsejo_FechaGDrive { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SeguimientoJASS SeguimientoJASS { get; set; }
        public virtual TipoSeguimiento TipoSeguimiento { get; set; }
        public virtual TipoBienArticulo TipoBienArticulo { get; set; }
    }
}
