//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_transferencias_sav
    {
        public int idtransferencia { get; set; }
        public string constante { get; set; }
        public string documentonumero { get; set; }
        public Nullable<System.DateTime> documentofecha { get; set; }
        public string codigomoneda { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> saldomoneda { get; set; }
        public string idfase { get; set; }
        public Nullable<decimal> montomoneda { get; set; }
        public string numerosiaf { get; set; }
        public string snip { get; set; }
        public Nullable<System.DateTime> dfecha_add { get; set; }
    }
}
