//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSeguimientoActividadesATM
    {
        public int IdDetalleSeguimientoActividadesATM { get; set; }
        public int IdSeguimientoActividadesATM { get; set; }
        public int IdCronogramaActividades { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NroHombres { get; set; }
        public Nullable<int> NroMujeres { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual CronogramaActividades CronogramaActividades { get; set; }
        public virtual SeguimientoActividadesATM SeguimientoActividadesATM { get; set; }
    }
}
