//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_transferencias_sav
    {
        public int idtransferencia { get; set; }
        public string constante { get; set; }
        public string documentonumero { get; set; }
        public Nullable<System.DateTime> documentofecha { get; set; }
        public string codigomoneda { get; set; }
        public string moneda { get; set; }
        public Nullable<decimal> saldomoneda { get; set; }
        public string idfase { get; set; }
        public Nullable<decimal> montomoneda { get; set; }
        public string numerosiaf { get; set; }
        public string snip { get; set; }
        public Nullable<System.DateTime> dfecha_add { get; set; }
    }
}
