//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSeguimientoATM
    {
        public int IdDetalleSeguimientoATM { get; set; }
        public int IdSeguimientoATM { get; set; }
        public int IdTipoSeguimiento { get; set; }
        public int IdTipoBienArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string InformeConformidadAC_HT { get; set; }
        public string InformeConformidadAC_Nro { get; set; }
        public Nullable<System.DateTime> InformeConformidadAC_Fecha { get; set; }
        public Nullable<System.DateTime> InformeConformidadAC_FechaGDrive { get; set; }
        public string ActaEntrega_Nro { get; set; }
        public Nullable<System.DateTime> ActaEntrega_Fecha { get; set; }
        public Nullable<System.DateTime> ActaEntrega_FechaGDrive { get; set; }
        public string AcuerdoConsejo_Nro { get; set; }
        public Nullable<System.DateTime> AcuerdoConsejo_Fecha { get; set; }
        public Nullable<System.DateTime> AcuerdoConsejo_FechaGDrive { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual TipoSeguimiento TipoSeguimiento { get; set; }
        public virtual TipoBienArticulo TipoBienArticulo { get; set; }
        public virtual SeguimientoATM SeguimientoATM { get; set; }
    }
}
