//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevengadoMensual
    {
        public int IdDevengadoMensual { get; set; }
        public int IdSeguimientoEjecucionProyectosInversion { get; set; }
        public Nullable<decimal> DevengadoAcumulado { get; set; }
        public Nullable<decimal> DiferenciaGasto { get; set; }
        public Nullable<decimal> PorcentajeAvanceGasto { get; set; }
        public string DetalleGastoMensual { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SeguimientoEjecucionProyectosInversion SeguimientoEjecucionProyectosInversion { get; set; }
    }
}
