//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevengadoMensual
    {
        public int IdDevengadoMensual { get; set; }
        public int IdSeguimientoEjecucionProyectosInversion { get; set; }
        public Nullable<decimal> DevengadoAcumulado { get; set; }
        public Nullable<decimal> DiferenciaGasto { get; set; }
        public Nullable<decimal> PorcentajeAvanceGasto { get; set; }
        public string DetalleGastoMensual { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SeguimientoEjecucionProyectosInversion SeguimientoEjecucionProyectosInversion { get; set; }
    }
}
