//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public string cod_depa { get; set; }
        public string cod_prov { get; set; }
        public string cod_dist { get; set; }
        public string nom_dist { get; set; }
        public string capital { get; set; }
    }
}
