//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public string cod_depa { get; set; }
        public string cod_prov { get; set; }
        public string cod_dist { get; set; }
        public string nom_dist { get; set; }
        public string capital { get; set; }
    }
}
