//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO_SUSTENTO
    {
        public int IDDOCUMENTO_SUSTENTO { get; set; }
        public Nullable<int> IDAUTORIZACION { get; set; }
        public string NOMBRE_DOCUMENTO { get; set; }
        public string ADJUNTO_DOCUMENTO { get; set; }
        public string DESCRIPCION_DOCUMENTO { get; set; }
        public Nullable<int> IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public Nullable<int> IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
    }
}
