//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EjecucionInversion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EjecucionInversion()
        {
            this.EjecucionInversionMes = new HashSet<EjecucionInversionMes>();
        }
    
        public int IdEjecucionInversion { get; set; }
        public Nullable<int> IdCategoriaGasto { get; set; }
        public string CategoriaGasto { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string GenericaGasto { get; set; }
        public decimal PIM { get; set; }
        public decimal Certificado { get; set; }
        public decimal AvanceCertificadoPorcentage { get; set; }
        public decimal Compromiso { get; set; }
        public decimal AvanceCompromiso { get; set; }
        public decimal Devengado { get; set; }
        public decimal AvanceDevengadoPorcentage { get; set; }
        public Nullable<int> Anio { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EjecucionInversionMes> EjecucionInversionMes { get; set; }
    }
}
