//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EjecucionInversionMes
    {
        public int IdEjecucionInversionMes { get; set; }
        public int IdEjecucionInversion { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal ProgramadoMes { get; set; }
        public decimal EjecutadoMes { get; set; }
        public decimal Porcentage { get; set; }
        public decimal PorEjecutar { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        public virtual EjecucionInversion EjecucionInversion { get; set; }
    }
}
