//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMontoProyectoVSPresupuesto
    {
        public int IdProyecto { get; set; }
        public string Programa { get; set; }
        public string Ubigeo { get; set; }
        public string cod_dep { get; set; }
        public string cod_prov { get; set; }
        public string cod_dist { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string Localidad { get; set; }
        public string Snip { get; set; }
        public string CUI { get; set; }
        public string Nom_proyecto { get; set; }
        public Nullable<decimal> Mto_proyecto { get; set; }
        public decimal Presupuesto { get; set; }
        public decimal Porcentaje { get; set; }
        public int Correcto { get; set; }
    }
}
