//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEstadoActividad
    {
        public int IdProyecto { get; set; }
        public string SNIP { get; set; }
        public string CUI { get; set; }
        public string Ubigeo { get; set; }
        public string cod_dep { get; set; }
        public string cod_prov { get; set; }
        public string cod_dist { get; set; }
        public string PROGRAMA { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string PROYECTO { get; set; }
        public string LOCALIDAD { get; set; }
        public string MTO_PROYECTO { get; set; }
        public string TOTAL_AUTORIZACION { get; set; }
        public string TOTAL_MANIFIESTO { get; set; }
        public string fecha_ult_act { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
