//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANIFIESTO_GASTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANIFIESTO_GASTO()
        {
            this.MANIFIESTO_GASTO_DETALLE = new HashSet<MANIFIESTO_GASTO_DETALLE>();
        }
    
        public int IDMANIFIESTO { get; set; }
        public string NRO_MANIFIESTO { get; set; }
        public int IDPROYECTO { get; set; }
        public Nullable<System.DateTime> FECHA_MANIFIESTO { get; set; }
        public string RUBRO { get; set; }
        public string CORRESPONDE_AL_MES { get; set; }
        public Nullable<int> CORRESPONDE_AL_ANIO { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<decimal> MONTO_ACUMULADO_MANIFIESTOS_ANTERIORES { get; set; }
        public Nullable<decimal> MONTO_MANIFIESTO { get; set; }
        public Nullable<decimal> MONTO_DESPUES_MANIFIESTO { get; set; }
        public Nullable<int> ESTADO_DOCUMENTO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public int IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public int IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
        public Nullable<int> TIPO_MANIFIESTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANIFIESTO_GASTO_DETALLE> MANIFIESTO_GASTO_DETALLE { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
