//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuSistema()
        {
            this.PerfilMenu = new HashSet<PerfilMenu>();
        }
    
        public int IdMenuSistema { get; set; }
        public string Titulo_padre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdMenu_padre { get; set; }
        public string Url { get; set; }
        public Nullable<int> Menu_jerarquia { get; set; }
        public string Icono { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilMenu> PerfilMenu { get; set; }
    }
}
