//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Sistema
    {
        public int IdOpcion { get; set; }
        public string Descripcion { get; set; }
        public int IdOpcion_Padre { get; set; }
        public string Url { get; set; }
        public int Menu_Jerarquia { get; set; }
        public string Icono { get; set; }
    }
}
