//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Sistema
    {
        public int IdOpcion { get; set; }
        public string Descripcion { get; set; }
        public int IdOpcion_Padre { get; set; }
        public string Url { get; set; }
        public int Menu_Jerarquia { get; set; }
        public string Icono { get; set; }
    }
}
