//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Documento_Detalle
    {
        public int IdDocumento_detalle { get; set; }
        public int IdMovimiento { get; set; }
        public string Nombre_documento { get; set; }
        public string Nombre_real_documento { get; set; }
        public string Ruta_documento { get; set; }
        public string Cod_pagina { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Movimiento_Documento Movimiento_Documento { get; set; }
    }
}
