//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento_Documento()
        {
            this.Movimiento_Documento_Detalle = new HashSet<Movimiento_Documento_Detalle>();
        }
    
        public int IdMovimiento { get; set; }
        public int IdProyecto { get; set; }
        public string Tipo_documento { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdMovimiento_anterior { get; set; }
        public Nullable<int> Tipo_envia_documento { get; set; }
        public Nullable<int> IdUsuario_envia_documento { get; set; }
        public Nullable<System.DateTime> Fecha_envia_documento { get; set; }
        public Nullable<int> Tipo_recibe_documento { get; set; }
        public Nullable<int> IdUsuario_recibe_documento { get; set; }
        public Nullable<System.DateTime> Fecha_recibe_documento { get; set; }
        public Nullable<System.DateTime> Fecha_atiende_documento { get; set; }
        public string Observacion_documento { get; set; }
        public string Nombre_documento_aprobacion { get; set; }
        public string Adjunto_observacion { get; set; }
        public Nullable<int> Estado_documento { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Orden_envia { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
        public string Ruta_laserfiche { get; set; }
        public string Nombre_documento_laserfiche { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento_Documento_Detalle> Movimiento_Documento_Detalle { get; set; }
    }
}
