//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PebsOperacion
    {
        public int nIdOperacion { get; set; }
        public string sNameSP { get; set; }
        public string sDescripcion { get; set; }
        public bool bestado { get; set; }
    }
}
