//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilMenu
    {
        public int IdPerfilMenu { get; set; }
        public int IdPerfil { get; set; }
        public int IdMenuSistema { get; set; }
        public Nullable<bool> Permiso_lectura { get; set; }
        public Nullable<bool> Permiso_escritura { get; set; }
        public Nullable<bool> Permiso_eliminar { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        public virtual MenuSistema MenuSistema { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
