//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaFamilia
    {
        public int IdPersonaFamilia { get; set; }
        public int IdPersona { get; set; }
        public Nullable<int> TipoFamiliar { get; set; }
        public string ApePaterno { get; set; }
        public string ApeMaterno { get; set; }
        public string Nombres { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string UbigeoDireccion { get; set; }
        public string Direccion { get; set; }
        public string Referencia { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public Nullable<bool> Emergencia { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
