//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_LIQUIDACION_MENSUAL
    {
        public int IDPRE_LIQUIDACION_MENSUAL { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public Nullable<int> IDMANIFIESTO { get; set; }
        public string MES_PRELIQUIDACION_MENSUAL { get; set; }
        public Nullable<decimal> DESEMBOLSADO_ACUMULADO_NE { get; set; }
        public Nullable<decimal> DESEMBOLSO_MES { get; set; }
        public Nullable<decimal> OTROS_APORTES_MES { get; set; }
        public Nullable<decimal> INTERES_MES { get; set; }
        public Nullable<decimal> DEVOLUCION_PROGRAMA { get; set; }
        public Nullable<decimal> MONTO_EJECUTADO_MES { get; set; }
        public Nullable<decimal> MONTO_EJECUTADO_ACUMULADO { get; set; }
        public Nullable<int> ESTADO_COORDINADOR { get; set; }
        public Nullable<int> ESTADO_LIQUIDADOR { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION_PRELIQUIDACION { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public Nullable<int> IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
