//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto_obra
    {
        public int IdPresupuesto { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string Nro_presupuesto { get; set; }
        public Nullable<int> Cod_presupuesto { get; set; }
        public Nullable<int> Cod_partida { get; set; }
        public Nullable<int> Cod_subpartida { get; set; }
        public Nullable<System.DateTime> Fecha_presupuesto { get; set; }
        public Nullable<decimal> Porcentaje_presupuesto { get; set; }
        public Nullable<decimal> Costo_total_presupuesto { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    }
}
