//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto_obra_detalle
    {
        public int Id_presupuesto_obra_detalle { get; set; }
        public Nullable<int> IdPresupuesto { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public string Item_actividad { get; set; }
        public string Descripcion_actividad { get; set; }
        public string Item { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad_metrado { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Costo_unitario_precio { get; set; }
        public Nullable<decimal> Parcial { get; set; }
        public string Etapa { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Agregado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual Presupuesto_obra Presupuesto_obra { get; set; }
    }
}
