//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO_OBRA_DETALLE_AGRUPADO
    {
        public int ID_PRESUPUESTO_OBRA_DETALLE_AGRUPADO { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public Nullable<int> IDRUBRO { get; set; }
        public string ITEM { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> COSTO_UNITARIO_PRECIO { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_ORIGINAL { get; set; }
        public Nullable<decimal> PARCIAL_ORIGINAL { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_ACUMULADO_AUTORIZACION_REAL { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_ACUMULADO_AUTORIZACION { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_DISPONIBLE_AUTORIZACION_REAL { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_DISPONIBLE_AUTORIZACION { get; set; }
        public Nullable<decimal> PARCIAL_ACUMULADO_AUTORIZACION_REAL { get; set; }
        public Nullable<decimal> PARCIAL_ACUMULADO_AUTORIZACION { get; set; }
        public Nullable<decimal> PARCIAL_DISPONIBLE_AUTORIZACION_REAL { get; set; }
        public Nullable<decimal> PARCIAL_DISPONIBLE_AUTORIZACION { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_ACUMULADO_MANIFIESTO_REAL { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_ACUMULADO_MANIFIESTO { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_DISPONIBLE_MANIFIESTO_REAL { get; set; }
        public Nullable<decimal> CANTIDAD_METRADO_DISPONIBLE_MANIFIESTO { get; set; }
        public Nullable<decimal> PARCIAL_ACUMULADO_MANIFIESTO_REAL { get; set; }
        public Nullable<decimal> PARCIAL_ACUMULADO_MANIFIESTO { get; set; }
        public Nullable<decimal> PARCIAL_DISPONIBLE_MANIFIESTO_REAL { get; set; }
        public Nullable<decimal> PARCIAL_DISPONIBLE_MANIFIESTO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public Nullable<int> IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
    }
}
