//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto_obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuesto_obra()
        {
            this.Presupuesto_obra_detalle = new HashSet<Presupuesto_obra_detalle>();
        }
    
        public int IdPresupuesto { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string Nro_presupuesto { get; set; }
        public Nullable<int> Cod_presupuesto { get; set; }
        public Nullable<int> Cod_partida { get; set; }
        public Nullable<int> Cod_subpartida { get; set; }
        public Nullable<System.DateTime> Fecha_presupuesto { get; set; }
        public Nullable<decimal> Porcentaje_presupuesto { get; set; }
        public Nullable<decimal> Costo_total_presupuesto { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuesto_obra_detalle> Presupuesto_obra_detalle { get; set; }
    }
}
