//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceso()
        {
            this.ProcesoDetalle = new HashSet<ProcesoDetalle>();
        }
    
        public int IdProceso { get; set; }
        public int IdComponente { get; set; }
        public string NroProceso { get; set; }
        public string NombreProceso { get; set; }
        public int IdIndicador { get; set; }
        public Nullable<int> AnioProceso { get; set; }
        public Nullable<int> TipoAntiguedad { get; set; }
        public decimal MontoProceso { get; set; }
        public int IdUnidadResponsable { get; set; }
        public string Responsable1 { get; set; }
        public string Responsable2 { get; set; }
        public int TipoProceso { get; set; }
        public Nullable<int> EstrategiaProcesoAdquisicion { get; set; }
        public string Hito1 { get; set; }
        public string Hito2 { get; set; }
        public Nullable<int> ElaboroETTDR { get; set; }
        public bool Revisado { get; set; }
        public int Estado { get; set; }
        public bool HT { get; set; }
        public string NumeroHT { get; set; }
        public bool CCP { get; set; }
        public string Observacion { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario_add { get; set; }
        public System.DateTime Fecha_add { get; set; }
        public int IdUsuario_upd { get; set; }
        public System.DateTime Fecha_upd { get; set; }
    
        public virtual Componente Componente { get; set; }
        public virtual Indicador Indicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoDetalle> ProcesoDetalle { get; set; }
    }
}
