//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramadoEjecutadoMensual
    {
        public int IdProgramadoEjecutadoMensual { get; set; }
        public int IdSeguimientoEjecucionProyectosInversion { get; set; }
        public Nullable<decimal> ProgramadoMes { get; set; }
        public Nullable<decimal> ProgramadoSemanaUno { get; set; }
        public Nullable<decimal> EjecutadoSemanaUno { get; set; }
        public Nullable<decimal> ProgramadoSemanaDos { get; set; }
        public Nullable<decimal> EjecutadoSemanaDos { get; set; }
        public Nullable<decimal> ProgramadoSemanaTres { get; set; }
        public Nullable<decimal> EjecutadoSemanaTres { get; set; }
        public Nullable<decimal> ProgramadoSemanaCuatro { get; set; }
        public Nullable<decimal> EjecutadoSemanaCuatro { get; set; }
        public Nullable<decimal> ProgramadoSemanaCinco { get; set; }
        public Nullable<decimal> EjecutadoSemanaCinco { get; set; }
        public Nullable<decimal> TotalProgramado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SeguimientoEjecucionProyectosInversion SeguimientoEjecucionProyectosInversion { get; set; }
    }
}
