//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramadoEjecutadoMensual
    {
        public int IdProgramadoEjecutadoMensual { get; set; }
        public int IdSeguimientoEjecucionProyectosInversion { get; set; }
        public Nullable<decimal> ProgramadoMes { get; set; }
        public Nullable<decimal> ProgramadoSemanaUno { get; set; }
        public Nullable<decimal> EjecutadoSemanaUno { get; set; }
        public Nullable<decimal> ProgramadoSemanaDos { get; set; }
        public Nullable<decimal> EjecutadoSemanaDos { get; set; }
        public Nullable<decimal> ProgramadoSemanaTres { get; set; }
        public Nullable<decimal> EjecutadoSemanaTres { get; set; }
        public Nullable<decimal> ProgramadoSemanaCuatro { get; set; }
        public Nullable<decimal> EjecutadoSemanaCuatro { get; set; }
        public Nullable<decimal> ProgramadoSemanaCinco { get; set; }
        public Nullable<decimal> EjecutadoSemanaCinco { get; set; }
        public Nullable<decimal> TotalProgramado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SeguimientoEjecucionProyectosInversion SeguimientoEjecucionProyectosInversion { get; set; }
    }
}
