//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgresoSubComponente
    {
        public int IdProgresoSubComponente { get; set; }
        public Nullable<int> IdSubComponente { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> PA { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> PorcentajeProgreso { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual SubComponente SubComponente { get; set; }
    }
}
