//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Autorizacion_Gasto = new HashSet<Autorizacion_Gasto>();
            this.Desembolso = new HashSet<Desembolso>();
            this.DesembolsoProgramadoAnual = new HashSet<DesembolsoProgramadoAnual>();
            this.MANIFIESTO_GASTO = new HashSet<MANIFIESTO_GASTO>();
            this.MonitoreoObras = new HashSet<MonitoreoObras>();
            this.PersonaProyecto = new HashSet<PersonaProyecto>();
            this.AsignacionProyecto_Personal = new HashSet<AsignacionProyecto_Personal>();
            this.CronogramaAdquisicionInsumos = new HashSet<CronogramaAdquisicionInsumos>();
            this.PRE_LIQUIDACION_MENSUAL = new HashSet<PRE_LIQUIDACION_MENSUAL>();
        }
    
        public int IdProyecto { get; set; }
        public Nullable<int> Act_proy { get; set; }
        public Nullable<int> Cod_programa { get; set; }
        public Nullable<int> Cod_subprograma { get; set; }
        public string Nom_proyecto { get; set; }
        public string IdUbigeo { get; set; }
        public string Localidad { get; set; }
        public Nullable<int> Cod_modalidad { get; set; }
        public string Snip { get; set; }
        public Nullable<System.DateTime> Fecha_aprobacion_epi { get; set; }
        public Nullable<decimal> Monto_aprobacion_epi { get; set; }
        public Nullable<System.DateTime> Fecha_verificacion_epi { get; set; }
        public Nullable<decimal> Monto_verificacion_epi { get; set; }
        public Nullable<int> Nro_beneficiarios_epi { get; set; }
        public string Documento_aprobacion_et { get; set; }
        public Nullable<System.DateTime> Fecha_aprobacion_et { get; set; }
        public Nullable<decimal> Monto_aprobacion_et { get; set; }
        public Nullable<int> Nro_beneficiarios_et { get; set; }
        public Nullable<int> Nro_conexiones_agua_et { get; set; }
        public Nullable<int> Nro_conexiones_saneamiento_et { get; set; }
        public Nullable<int> Plazo_ejecucion_et { get; set; }
        public string Num_convenio_ne { get; set; }
        public Nullable<System.DateTime> Fecha_suscripcion_convenio { get; set; }
        public string Nombre_ne { get; set; }
        public string Nom_cuenta { get; set; }
        public string Num_cta_ahorros { get; set; }
        public Nullable<System.DateTime> Fecha_inicio_programado { get; set; }
        public Nullable<System.DateTime> Fecha_inicio_real { get; set; }
        public Nullable<System.DateTime> Fecha_fin_programado { get; set; }
        public Nullable<System.DateTime> Fecha_fin_real { get; set; }
        public Nullable<int> Plazo_ejecucion_obra { get; set; }
        public Nullable<System.DateTime> Fecha_estimada_termino_ampliacion { get; set; }
        public Nullable<System.DateTime> Fecha_estimada_termino_ampliacion_paralizacion { get; set; }
        public Nullable<decimal> Mto_proyecto { get; set; }
        public Nullable<decimal> Saldo_disponible_real { get; set; }
        public Nullable<decimal> Saldo_disponible { get; set; }
        public Nullable<decimal> Monto_acumulado_autorizacion_real { get; set; }
        public Nullable<decimal> Monto_acumulado_autorizacion { get; set; }
        public Nullable<decimal> Monto_acumulado_manifiesto_gasto_real { get; set; }
        public Nullable<decimal> Monto_acumulado_manifiesto_gasto { get; set; }
        public Nullable<decimal> Monto_transferido { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
        public Nullable<System.DateTime> Fecha_aprobación_informe_inicial { get; set; }
        public Nullable<System.DateTime> Fecha_aprobación_primer_retiro_fondos { get; set; }
        public string CUI { get; set; }
        public Nullable<decimal> CostoInversionActualizado { get; set; }
        public Nullable<decimal> MontoDesembolso { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public string Liquidador { get; set; }
        public Nullable<int> AnioEjecucion { get; set; }
        public string Grupo { get; set; }
        public Nullable<System.DateTime> FechaCulminacionObra { get; set; }
        public Nullable<int> PoblacionBeneficiaria { get; set; }
        public Nullable<int> NroConexionesAgua { get; set; }
        public Nullable<int> NroConexionesUBS { get; set; }
        public Nullable<int> NroViviendas { get; set; }
        public Nullable<int> ViviendasUtilizanUBS { get; set; }
        public Nullable<int> CantidadMujeresJASS { get; set; }
        public Nullable<System.DateTime> FechaCantidadMujeres { get; set; }
        public Nullable<int> CantidadMujeresNE { get; set; }
        public Nullable<System.DateTime> FechaCantidadMujeresNE { get; set; }
        public Nullable<System.DateTime> FechaInicioOTA { get; set; }
        public Nullable<System.DateTime> FechaFinOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacion_Gasto> Autorizacion_Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desembolso> Desembolso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesembolsoProgramadoAnual> DesembolsoProgramadoAnual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANIFIESTO_GASTO> MANIFIESTO_GASTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoreoObras> MonitoreoObras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaProyecto> PersonaProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionProyecto_Personal> AsignacionProyecto_Personal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CronogramaAdquisicionInsumos> CronogramaAdquisicionInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRE_LIQUIDACION_MENSUAL> PRE_LIQUIDACION_MENSUAL { get; set; }
    }
}
