//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoEsperado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultadoEsperado()
        {
            this.ResultadoEsperadoAnio = new HashSet<ResultadoEsperadoAnio>();
        }
    
        public int IdResultadoEsperado { get; set; }
        public int IdMatrizResultado { get; set; }
        public Nullable<int> NroResultadoEsperado { get; set; }
        public string ResultadoEsperado1 { get; set; }
        public Nullable<int> LineaBase { get; set; }
        public Nullable<int> AnioLineaBase { get; set; }
        public string UnidadMedida { get; set; }
        public string MedioVerificacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual MatrizResultado MatrizResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoEsperadoAnio> ResultadoEsperadoAnio { get; set; }
    }
}
