//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoEsperado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultadoEsperado()
        {
            this.ResultadoEsperadoAnio = new HashSet<ResultadoEsperadoAnio>();
        }
    
        public int IdResultadoEsperado { get; set; }
        public int IdMatrizResultado { get; set; }
        public Nullable<int> NroResultadoEsperado { get; set; }
        public string ResultadoEsperado1 { get; set; }
        public Nullable<int> LineaBase { get; set; }
        public Nullable<int> AnioLineaBase { get; set; }
        public string UnidadMedida { get; set; }
        public string MedioVerificacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        public virtual MatrizResultado MatrizResultado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoEsperadoAnio> ResultadoEsperadoAnio { get; set; }
    }
}
