//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_ESTADO_FINANCIERO
    {
        public int IDRESUMEN_FINANCIERO { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public Nullable<int> ANIO { get; set; }
        public string MES { get; set; }
        public Nullable<int> ESTADO_RESUMEN { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public Nullable<int> IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public Nullable<int> IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
    }
}
