//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_SISTEMA
    {
        public int IDRoles { get; set; }
        public string sRoles { get; set; }
        public Nullable<int> nEstado { get; set; }
    }
}
