//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoDetalleArchivo
    {
        public int IdSeguimientoDetalleArchivo { get; set; }
        public string TipoSeguimiento { get; set; }
        public Nullable<int> IdSeguimiento { get; set; }
        public Nullable<int> IdDetalleSeguimiento { get; set; }
        public string NombreArchivo { get; set; }
        public string NombreRealArchivo { get; set; }
        public string FolderPath { get; set; }
        public string TamanioArchivo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    }
}
