//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoActividadesFamilias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoActividadesFamilias()
        {
            this.DetalleSeguimientoActividadesFamilias = new HashSet<DetalleSeguimientoActividadesFamilias>();
        }
    
        public int IdSeguimientoActividades { get; set; }
        public string CUI { get; set; }
        public string Paquete { get; set; }
        public Nullable<int> NroPoblacionMujeres { get; set; }
        public Nullable<int> NroPoblaciónHombres { get; set; }
        public Nullable<int> NroUsuariosMujeres { get; set; }
        public Nullable<int> NroUsuariosHombres { get; set; }
        public Nullable<int> NroPoblacionFlotante { get; set; }
        public Nullable<int> NroTotalViviendasValidadas { get; set; }
        public Nullable<int> NroTotalInstitucionesValidadas { get; set; }
        public Nullable<int> NroCentrosEducativos { get; set; }
        public string NivelCentrosEducativos { get; set; }
        public string CentroSalud { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSeguimientoActividadesFamilias> DetalleSeguimientoActividadesFamilias { get; set; }
    }
}
