//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoCuotaFamiliarJASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoCuotaFamiliarJASS()
        {
            this.DetalleSeguimientoCuotaFamiliarJASS = new HashSet<DetalleSeguimientoCuotaFamiliarJASS>();
        }
    
        public int IdSeguimientoCuotaFamiliarJASS { get; set; }
        public string CUI { get; set; }
        public string MSICargo { get; set; }
        public Nullable<decimal> MontoCuotaFamiliar { get; set; }
        public string NombreApellidosOperadorAyS { get; set; }
        public Nullable<bool> RecibeRenumerativo { get; set; }
        public Nullable<decimal> MontoRemunerativo { get; set; }
        public Nullable<decimal> CuotaFondoContigenciaMontoPlanificado { get; set; }
        public Nullable<decimal> CuotaFondoContigenciaMontoCobrado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSeguimientoCuotaFamiliarJASS> DetalleSeguimientoCuotaFamiliarJASS { get; set; }
    }
}
