//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoActividadesJASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoActividadesJASS()
        {
            this.DetalleSeguimientoActividadesJASS = new HashSet<DetalleSeguimientoActividadesJASS>();
        }
    
        public int IdSeguimientoActividadesJASS { get; set; }
        public string CUI { get; set; }
        public Nullable<int> NroAsociadosMujeres { get; set; }
        public Nullable<int> NroAsociadosHombres { get; set; }
        public Nullable<int> TotalViviendasValidadas { get; set; }
        public Nullable<int> TotalInstitucionesValidadas { get; set; }
        public Nullable<int> NroOperadoresSAPMujeres { get; set; }
        public Nullable<int> NroOperadoresSAPHombres { get; set; }
        public Nullable<int> TotalAutoridadesLideres { get; set; }
        public Nullable<int> NroIdentificacionLideres { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSeguimientoActividadesJASS> DetalleSeguimientoActividadesJASS { get; set; }
    }
}
