//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoActividadesNE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoActividadesNE()
        {
            this.DetalleSeguimientoActividadesNE = new HashSet<DetalleSeguimientoActividadesNE>();
        }
    
        public int IdSeguimientoActividadesNE { get; set; }
        public string CUI { get; set; }
        public Nullable<int> NroMienbrosMujeres { get; set; }
        public Nullable<int> NroMienbrosHombres { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSeguimientoActividadesNE> DetalleSeguimientoActividadesNE { get; set; }
    }
}
