//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoDetalleArchivo
    {
        public int IdSeguimientoDetalleArchivo { get; set; }
        public string TipoSeguimiento { get; set; }
        public Nullable<int> IdSeguimiento { get; set; }
        public Nullable<int> IdDetalleSeguimiento { get; set; }
        public string NombreArchivo { get; set; }
        public string NombreRealArchivo { get; set; }
        public string FolderPath { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    }
}
