//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubComponente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubComponente()
        {
            this.ProgresoSubComponente = new HashSet<ProgresoSubComponente>();
        }
    
        public int IdSubComponente { get; set; }
        public Nullable<int> IdTituloSubComponente { get; set; }
        public string NroSubComponente { get; set; }
        public string NombreSubComponente { get; set; }
        public string Indicador { get; set; }
        public string Unidad { get; set; }
        public string Progreso { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario_add { get; set; }
        public Nullable<System.DateTime> Fecha_add { get; set; }
        public Nullable<int> IdUsuario_upd { get; set; }
        public Nullable<System.DateTime> Fecha_upd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgresoSubComponente> ProgresoSubComponente { get; set; }
        public virtual TituloSubComponente TituloSubComponente { get; set; }
    }
}
