//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA_DETALLE
    {
        public int IDDETALLE { get; set; }
        public int IDTABLA { get; set; }
        public string SDETALLE { get; set; }
        public string FILLER1 { get; set; }
        public string FILLER2 { get; set; }
        public System.DateTime FECINS { get; set; }
        public System.DateTime FECUPD { get; set; }
        public int NESTADO { get; set; }
        public Nullable<int> IDPADRE { get; set; }
    
        public virtual TABLA TABLA { get; set; }
    }
}
