//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLA()
        {
            this.TABLA_DETALLE = new HashSet<TABLA_DETALLE>();
        }
    
        public int IDTABLA { get; set; }
        public string STABLA { get; set; }
        public string Label1_Text { get; set; }
        public string Label2_Text { get; set; }
        public string Label3_Text { get; set; }
        public int Label1_Width { get; set; }
        public int Label2_Width { get; set; }
        public int Label3_Width { get; set; }
        public Nullable<int> Label1_Lenght { get; set; }
        public Nullable<int> Label2_Lenght { get; set; }
        public Nullable<int> Label3_Lenght { get; set; }
        public int NESTADO { get; set; }
        public Nullable<int> IDPADRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLA_DETALLE> TABLA_DETALLE { get; set; }
    }
}
