//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_SISTEMA
    {
        public int IDUSUARIO { get; set; }
        public string PERSONAL { get; set; }
        public string USUARIO { get; set; }
        public byte[] CONTRASENA { get; set; }
        public Nullable<int> IDROL { get; set; }
        public int IDPERSONAL { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCIDAD { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<int> IDUSUARIO_ADD { get; set; }
        public Nullable<System.DateTime> FECHA_ADD { get; set; }
        public Nullable<int> IDUSUARIO_UPD { get; set; }
        public Nullable<System.DateTime> FECHA_UPD { get; set; }
        public string Password { get; set; }
    }
}
